from typing import Dict, Union, List, Optional
TABLE_TO_PHASE: Dict[str, Union[str, List[str]]] = {
    'accountStatus': 'phase1',
    'amountAboveRate': 'phase1',
    'amountFixedRate': 'phase1',
    'amountOffRate': 'phase1',
    'cleaningSchedule': 'phase1',
    'company': 'phase1',
    'confirmationNumber': ['phase1', 'phase2'],
    'contact': 'phase1',
    'contactPurpose': 'phase1',
    'creditCard': 'phase1',
    'customer': 'phase1',
    'extraCharge': 'phase1',
    'folioItem': 'phase1',
    'folioSummary': 'phase1',
    'groupBlock': 'phase1',
    'groupRate': 'phase1',
    'guarantee': 'phase1',
    'hotel': 'phase1',
    'linkedReservation': 'phase1',
    'loyaltyRewardsMembership': 'phase1',
    'paymentMethod': 'phase1',
    'percentAboveRate': 'phase1',
    'percentOffRate': 'phase1',
    'ratePlanCode': 'phase1',
    'reservationItem': 'phase1',
    'reservationStatus': 'phase1',
    'reservedInventory': 'phase1',
    'reservedRate': 'phase1',
    'reservedRoom': 'phase1',
    'specialRequest': 'phase1',
    'travelAgent': 'phase1',
    'contactContactPurposeLink': 'phase2',
    'customerContactLink': 'phase2',
    'customerLoyaltyRewardsMembershipLink': 'phase2',
    'guaranteeCreditCardLink': 'phase2',
    'paymentMethodCreditCardLink': 'phase2',
    'reservationItemReservedInventoryLink': 'phase2',
    'reservationItemReservedRateLink': 'phase2',
    'reservationItemReservedRoomLink': 'phase2',
    'reservationItemSpecialRequestLink': 'phase2',
    'group': 'phase2',
    'rate': 'phase2',
    'housekeepingStatus': 'phase2',
    'inventoryAvailableCount': 'phase2',
    'inventoryBatch': 'phase2',
    'inventoryOutOfOrderCount': 'phase2',
    'inventoryPhysicalCount': 'phase2',
    'groupAccountStatusLink': 'phase3',
    'groupConfirmationNumberLink': 'phase3',
    'groupContactLink': 'phase3',
    'groupFolioItemLink': 'phase3',
    'groupFolioSummaryLink': 'phase3',
    'groupGroupBlockLink': 'phase3',
    'groupGroupRateLink': 'phase3',
    'groupGuestCreditCardLink': 'phase3',
    'groupLoyaltyRewardsMembershipLink': 'phase3',
    'groupPaymentMethodLink': 'phase3',
    'groupPlannerCreditCardLink': 'phase3',
    'housekeepingStatusConfirmationNumberLink': 'phase3',
    'rateAmountAboveRateLink': 'phase3',
    'rateAmountFixedRateLink': 'phase3',
    'rateAmountOffRateLink': 'phase3',
    'rateExtraChargeLink': 'phase3',
    'ratePercentAboveRateLink': 'phase3',
    'ratePercentOffRateLink': 'phase3',
    'rateRatePlanCodeLink': 'phase3',
    'reservation': 'phase3',
    'reservationCleaningScheduleLink': 'phase4',
    'reservationConfirmationNumberLink': 'phase4',
    'reservationCustomerLink': 'phase4',
    'reservationEmailAddressLink': 'phase4',
    'reservationFolioSummaryLink': 'phase4',
    'reservationGuaranteeLink': 'phase4',
    'reservationItemLink': 'phase4',
    'reservationLinkedReservationLink': 'phase4',
    'reservationPaymentMethodLink': 'phase4',
    'reservationStatusLink': 'phase4',
}


def get_table_phase(table_name: str) -> Optional[Union[str, List[str]]]:
    """
    Get the phase for a given table name.
    
    Returns:
        Phase string, list of phase strings if table appears in multiple phases,
        or None if table not found
    """
    return TABLE_TO_PHASE.get(table_name)